import { PERMISSIONS } from "@/shared/permissions";

export const CAR_PERMISSIONS = {
  READ: PERMISSIONS.FLEET_VIEW,
  CREATE: PERMISSIONS.FLEET_CREATE,
  UPDATE: PERMISSIONS.FLEET_EDIT,
  DELETE: PERMISSIONS.FLEET_DELETE,
  RESTORE: PERMISSIONS.FLEET_DELETE,
  MAINTENANCE: PERMISSIONS.FLEET_MAINTENANCE_CREATE,
  DOCUMENTS: PERMISSIONS.FLEET_EDIT,
  AVAILABILITY: PERMISSIONS.FLEET_MAINTENANCE_CREATE,
} as const;
